#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#user_bundle:
#    resource: '@UserBundle'
#    type: annotation

user_router:
    type: rest
    resource: App\User\Controller\UserController
    prefix: /user